### ISSUE TITLE
filament runout

### ISSUE THREAD

**Issue by Pieterjan070889** [Lash-L/Ender-3-V2-Neo-Setup#2]
I love this firmware, but I can't edit it. I have the creality runout sensor, can someone update this firmware for me?

**Comment by Lash-L** [comment]
Why are you not able to edit it? When you are adding parts yourself that need firmware changes, it is definitely important for you to know how to edit the configuration

**Comment by Lash-L** [comment]
@Pieterjan070889 I'm going to close out this thread if I don't hear from you before the end of this week.
