### ISSUE TITLE
firmware install

### ISSUE THREAD

**Issue by bengo06** [Lash-L/Ender-3-V2-Neo-Setup#3]
My firmware will not install to the printer. Anyone know what the issue may be? I think I did everything right.

**Comment by Lash-L** [comment]
Can you give a little more context? Whats happening when you install the sd card? Do you have everything you need to on the sd card?

**Comment by bengo06** [comment]
when i put in the sd card the screen just shows the creality logo. I have tried with the just the .bin on the card as well and that does not work either

**Comment by Lash-L** [comment]
Does it stay on the creality logo or does it eventually go to the main screen?

Have you tried renaming the .bin?

Are you sure you have your motherboard set to the correct version?

Is your sd card formatted correctly? Fat32 4096 allocation bytes?

**Comment by bengo06** [comment]
The creality logo stays on and it doesn’t go to the main screen. I believe I have it set to the right mobo and will double check. Do I have to rename the .bin to anything special? I have renamed it a few times.

**Comment by Lash-L** [comment]
Nope, you shouldn't need to rename it to anything special. Just a new name. How long do you wait on the Creality logo? do you have anything plugged into the printers micro usb?

**Comment by Lash-L** [comment]
@ImMrBalloon If I don't hear from you before the end of the week, I'm going to close this issue, otherwise I'm happy to try to help

**Comment by bengo06** [comment]
Oh, sorry I didn’t see your last reply! I got the firmware to work by renaming it to something shorter. Thanks for the help.
